// Generated by gencpp from file AUTMAV_msgs/TakeOffMsg.msg
// DO NOT EDIT!


#ifndef AUTMAV_MSGS_MESSAGE_TAKEOFFMSG_H
#define AUTMAV_MSGS_MESSAGE_TAKEOFFMSG_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace AUTMAV_msgs
{
template <class ContainerAllocator>
struct TakeOffMsg_
{
  typedef TakeOffMsg_<ContainerAllocator> Type;

  TakeOffMsg_()
    : height(0.0)
    , speed(0.0)  {
    }
  TakeOffMsg_(const ContainerAllocator& _alloc)
    : height(0.0)
    , speed(0.0)  {
  (void)_alloc;
    }



   typedef float _height_type;
  _height_type height;

   typedef float _speed_type;
  _speed_type speed;




  typedef boost::shared_ptr< ::AUTMAV_msgs::TakeOffMsg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::AUTMAV_msgs::TakeOffMsg_<ContainerAllocator> const> ConstPtr;

}; // struct TakeOffMsg_

typedef ::AUTMAV_msgs::TakeOffMsg_<std::allocator<void> > TakeOffMsg;

typedef boost::shared_ptr< ::AUTMAV_msgs::TakeOffMsg > TakeOffMsgPtr;
typedef boost::shared_ptr< ::AUTMAV_msgs::TakeOffMsg const> TakeOffMsgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::AUTMAV_msgs::TakeOffMsg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::AUTMAV_msgs::TakeOffMsg_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace AUTMAV_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'AUTMAV_msgs': ['/home/hojat/GS_WS/src/AUTMAV_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::AUTMAV_msgs::TakeOffMsg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::AUTMAV_msgs::TakeOffMsg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::AUTMAV_msgs::TakeOffMsg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::AUTMAV_msgs::TakeOffMsg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::AUTMAV_msgs::TakeOffMsg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::AUTMAV_msgs::TakeOffMsg_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::AUTMAV_msgs::TakeOffMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5921ebc5819641abaa902a006acf2460";
  }

  static const char* value(const ::AUTMAV_msgs::TakeOffMsg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5921ebc5819641abULL;
  static const uint64_t static_value2 = 0xaa902a006acf2460ULL;
};

template<class ContainerAllocator>
struct DataType< ::AUTMAV_msgs::TakeOffMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "AUTMAV_msgs/TakeOffMsg";
  }

  static const char* value(const ::AUTMAV_msgs::TakeOffMsg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::AUTMAV_msgs::TakeOffMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 height\n\
float32 speed\n\
";
  }

  static const char* value(const ::AUTMAV_msgs::TakeOffMsg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::AUTMAV_msgs::TakeOffMsg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.height);
      stream.next(m.speed);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TakeOffMsg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::AUTMAV_msgs::TakeOffMsg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::AUTMAV_msgs::TakeOffMsg_<ContainerAllocator>& v)
  {
    s << indent << "height: ";
    Printer<float>::stream(s, indent + "  ", v.height);
    s << indent << "speed: ";
    Printer<float>::stream(s, indent + "  ", v.speed);
  }
};

} // namespace message_operations
} // namespace ros

#endif // AUTMAV_MSGS_MESSAGE_TAKEOFFMSG_H
